sudo: required
language: csharp
dotnet: 1.0.4
mono:
  - 4.8.0
dist: trusty
os:
  - linux
script: 
  - dotnet restore
  - dotnet build src/Carable.AssemblyPayments
  - dotnet build test/Tests
  - cd test/Tests
  - dotnet test 
